# Copyright © 2025 Ed Nutting
# SPDX-License-Identifier: MIT
# See LICENSE file for details

# Transcription settings
transcription:
  provider: vosk # or "sherpa"
  model_id: vosk-en-us-small # See available models with: autocue --list-models
  model_path: null # Optional custom model path

# Legacy settings (deprecated, will be migrated automatically)
model: null
model_path: null

# Server settings
host: 127.0.0.1
port: 8000
audio_device: null
chunk_ms: 50

# Scripts folder (optional) - set to a folder path to show extra scripts in the UI
# Example: scripts_folder: C:\Users\YourName\Documents\Scripts
scripts_folder: null

# UI display settings
display:
  fontSize: 60
  fontFamily: Georgia, serif
  lineHeight: 1.6
  pastLines: 1
  futureLines: 8
  theme: dark
  highlightColor: "#FFD700"
  textColor: "#FFFFFF"
  dimColor: "#666666"
  backgroundColor: "#1a1a1a"
tracking:
  window_size: 8
  match_threshold: 85.0
  backtrack_threshold: 4
  max_jump_distance: 80
  max_skip_distance: 2
