model: medium
model_path: null
host: 127.0.0.1
port: 8000
audio_device: null
chunk_ms: 100
display:
  fontSize: 60
  fontFamily: Georgia, serif
  lineHeight: 1.6
  pastLines: 1
  futureLines: 8
  theme: dark
  highlightColor: "#FFD700"
  textColor: "#FFFFFF"
  dimColor: "#666666"
  backgroundColor: "#1a1a1a"
tracking:
  window_size: 8
  match_threshold: 85.0
  backtrack_threshold: 4
  max_jump_distance: 80
  max_skip_distance: 2
